import { Routes, Route, Navigate } from "react-router-dom";

// Хуки
import { PupilsList } from "./components/adminPages/pupils/PupilsList";

// Новые импорты
// Роутинг
import { AuthRouter } from "./routing/AuthRouter";
import { ProtectedRoute } from "./routing/ProtectedRoute";
import { RolesProtectedRoute } from "./routing/RolesProtectedRoute";

// Общий layout для страниц
import { Layout } from "./components/layout/Layout"

// Страницы
// Авторизация / Регистрация
import { LoginPage } from "./components/authorizationPages/LoginPage"
import { SpecialistRegistrationPage } from "./components/authorizationPages/SpecialistRegistrationPage"
import { PupilRegistrationPage } from "./components/authorizationPages/PupilRegistrationPage"

// Главные страницы
import { HomePage } from "./components/homePage/HomePage"
import { TestsPage } from "./components/testsPage/TestsPage"
import { ResultsPage } from "./components/resultsPage/ResultsPage"
import { StudyPage } from "./components/studyPage/StudyPage"
import { ProfileCommonPage } from "./components/profilePage/ProfileCommonPage"

// Админские страницы
import { AdminPage } from "./components/adminPages/AdminPage"
import { SimulationPage } from "./components/adminPages/simulations/SimulationsPage"
import { RegistrationTypePicker } from "./components/authorizationPages/RegistrationTypePage"
import { Specialists } from "./components/adminPages/specialists/Specialists"

// Outlet для тестов
import { TestViewer } from "./components/testsPage/TestViewer"

import { DownloadTestsResults } from "./components/adminPages/results/DownloadTestsResults";
import { crudRoutes } from "./components/adminPages/crud/routes.config";
import { FormsListPage } from "./components/adminPages/crud/FormsListPage";
import { Predictions } from "./components/predictions/Predictions";
import { VRTestsPage } from "./components/VRTestsPage/VRTestsPage";
import { VRTestIntro } from "./components/VRTestsPage/VRTestIntro";
import { VRTest } from "./components/VRTestsPage/VRTest";
import { VRTestResults } from "./components/VRTestsPage/results/VRTestResults";
import { CompanyManagement } from "./components/adminPages/companies/CompanyManagement";
import { SchoolManagement } from "./components/adminPages/schools/SchoolManagement";
import { CuratorDashboard } from "./components/curatorPages/CuratorDashboard";
import { TestTypeManagement } from "./components/adminPages/results/TestTypeManagement";
import { ADMIN_ROLES, CAREER_TEST_ROLES, CURATOR_ROLES, PUPIL_ONLY_ROLES } from "./routing/roleAccess";
import { TestRoutes } from "./routing/tests/TestRoutes";

export default function App() {
	return (
		<Routes>
			{/* Public routes */}
			<Route element={<Layout />}>
				<Route path="/" element={<HomePage />} />
			</Route>
			<Route element={<AuthRouter />}>
				<Route element={<Layout />}>
					<Route path="/login" element={<LoginPage />} />
					<Route path="/register" >
						<Route path="" element={<RegistrationTypePicker />} />
						<Route path="specialist" element={<SpecialistRegistrationPage />} />
						<Route path="pupil" element={<PupilRegistrationPage />} />
					</Route>

				</Route>
			</Route>

			{/* Protected routes */}
			<Route element={<ProtectedRoute />}>
				<Route element={<Layout />}>
					<Route element={<RolesProtectedRoute approvedRoles={ADMIN_ROLES} />}>
						<Route path="/admin" element={<AdminPage />}>
							<Route index element={<Navigate to="/admin/pupils" replace />} />

							<Route path="pupils-upload" element={<Navigate to="/admin/pupils" replace />} />
							<Route path="pupils" element={<PupilsList />} />

							<Route path="simulations" element={<SimulationPage />} />

							<Route path="specialists" element={<Specialists />} />
							<Route path="specialists-upload" element={<Navigate to="/admin/specialists" replace />} />

							<Route path="results" element={<DownloadTestsResults />} />
							{/* Admin CRUD routes from the existing templates */}
							<Route path="forms" element={<FormsListPage />} />
							{crudRoutes.map(route => (
								<Route key={route.path} path={route.path} element={<route.element />} />
							))}
							<Route path="companies" element={<CompanyManagement />} />
							<Route path="schools" element={<SchoolManagement />} />
							<Route path="test-types" element={<TestTypeManagement />} />

						</Route>
					</Route>
					{/* Curator Routes */}
					<Route element={<RolesProtectedRoute approvedRoles={CURATOR_ROLES} />}>
						<Route path="/curator" element={<CuratorDashboard />} />
					</Route>

					{/* Psychological tests autogenerated from testRoutes */}
					<Route element={<RolesProtectedRoute approvedRoles={CAREER_TEST_ROLES} />}>
						<Route path="/tests">
							<Route index element={<TestsPage/>}/>
							<Route element={<TestViewer/>} >
								{TestRoutes()}
							</Route>
							
						</Route>
						<Route path="/my-results" element={<ResultsPage />} />
						<Route path="/my-results/:testType" element={<ResultsPage />} />
					</Route>

					{/* VR tests routes*/}
					<Route element={<RolesProtectedRoute approvedRoles={CAREER_TEST_ROLES} />}>
						<Route path="/vr-tests">
							<Route index element={<VRTestsPage />} />
							<Route path=":profession/:professionId/intro" element={<VRTestIntro />} />
							<Route path=":profession/:professionId/questionnaire" element={<VRTest />} />
							<Route path=":profession/:professionId/results" element={<VRTestResults />} />
						</Route>
					</Route>

					{/* Results routes */}
					<Route element={<RolesProtectedRoute approvedRoles={PUPIL_ONLY_ROLES} />}>
						<Route path="/predictions" element={<Predictions />} />
						<Route path="/my-grades" element={<StudyPage />} />
					</Route>

					{/* Rest routes */}
					<Route path="/profile" element={<ProfileCommonPage />} />
				</Route>
			</Route>

			{/* Fallback routes */}
			<Route path="*" element={<Navigate to="/" replace />} />
		</Routes>
	);
}
